# Usando uma imagem base oficial do PHP
FROM php:8.1-apache

# Instalar extensões necessárias
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Copiar o código da aplicação para o diretório padrão do Apache
COPY src/php/ /var/www/html/

# Configurar permissões
RUN chown -R www-data:www-data /var/www/html
