version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./src/php:/var/www/html
    ports:
      - "80:80"
    
  node:
    build:
      context: .
      dockerfile: Dockerfile-node
    volumes:
      - ./src/node:/usr/src/app
    ports:
      - "3000:3000"
